TRUSTED_BRANDS = {
    "sbi": ["sbi.co.in", "onlinesbi.sbi", "onlinesbi.com"],
    "state bank of india": ["sbi.co.in", "onlinesbi.sbi", "onlinesbi.com"],
    "hdfc": ["hdfcbank.com"],
    "icici": ["icicibank.com"],
    "axis": ["axisbank.com"],
    "paytm": ["paytm.com"],
    "phonepe": ["phonepe.com"],
    "npci": ["npci.org.in"],
    "incometax": ["incometax.gov.in"],
    "uidai": ["uidai.gov.in"],
    "indiapost": ["indiapost.gov.in"],
    "irctc": ["irctc.co.in"],
    "amazon": ["amazon.in", "amazon.com"],
    "flipkart": ["flipkart.com"],
    "google": ["google.com", "google.co.in"],
    "microsoft": ["microsoft.com"],
    "apple": ["apple.com"],
    "iphone": ["apple.com"],
    "macbook": ["apple.com"],
    "ipad": ["apple.com"],
    "samsung": ["samsung.com"],
    "paypal": ["paypal.com"],
    "netflix": ["netflix.com"],
    "instagram": ["instagram.com"],
    "facebook": ["facebook.com"],
    "whatsapp": ["whatsapp.com"],
    "telegram": ["telegram.org"],
    "linkedin": ["linkedin.com"],
    "airtel": ["airtel.in"],
    "jio": ["jio.com"],
    "bsnl": ["bsnl.co.in"],
    "epfindia": ["epfindia.gov.in"],
    "punjab national bank": ["pnbindia.in"],
    "bank of baroda": ["bankofbaroda.in"],
    "kotak": ["kotak.com"],
    "swiggy": ["swiggy.com"],
    "zomato": ["zomato.com"],
}

SHORTENER_HOSTS = {
    "bit.ly",
    "tinyurl.com",
    "cutt.ly",
    "is.gd",
    "t.ly",
    "rb.gy",
    "ow.ly",
    "buff.ly",
    "soo.gd",
    "tiny.cc",
}

RISKY_TLDS = {
    "xyz",
    "top",
    "click",
    "shop",
    "icu",
    "buzz",
    "cfd",
    "sbs",
    "live",
    "rest",
    "monster",
}

SUSPICIOUS_PATH_WORDS = [
    "login",
    "verify",
    "secure",
    "update",
    "kyc",
    "wallet",
    "reward",
    "claim",
]
